server:
    port: 9031

spring:
    # 数据库配置
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/Violet?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: ahri
        password: ahri

mybatis:
    mapper-locations: classpath:mybatis/mapper/*Mapper.xml
    #    configuration:
    #        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    type-aliases-package: com.ahri.violetbackend.domain
    config-location: classpath:mybatis/mybatis-config.xml
